# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://movb.de" # the base hostname & protocol for your site
permalink: none

gems:
  - jekyll-sitemap

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Tobias <del>Mahnke-Nissen</del> König
  avatar: tobi-quadratisch.jpg
  gravatar: # Email MD5 hash
  description: "Private website of Tobias Mahnke-Nissen" # used by search engines

   # Header and footer text
  header_text: <blockquote cite="http://www.imdb.com/title/tt0086567/">Gentlemen, I wouldn't trust this overgrown pile of microchips any further than I can throw it.<footer>-- <cite>General Beringer, WarGames</cite></footer></blockquote>
  header_text_feature_image: img/bliss.jpg
  footer_text: Copyright &copy; 2015-2016 Tobias König &mdash; <a href="/about">About / Impressum</a>

  # Icons
  rss: false
  email_address: tn@movb.de
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "towbi"
  google_plus:
  instagram:
  linkedin: https://de.linkedin.com/in/tobiasnissen
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:
  xing: "Tobias_MahnkeNissen"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
