#!/bin/sh

set -eu

if test -z "$(git status --porcelain)"; then

    # regenerate site

    echo Regenerating site with Jekyll...
    jekyll build

    # update movb.de

    echo Rsyncing with movb.de...
    rsync -a --delete _site/ movb.de:www

else
    echo "Git reports unclean working copy -- can't continue."
fi

