#!/bin/sh


if test -z "$(git status --porcelain)"; then
  jekyll build
  git push
  rsync -a --delete _site/ movb.de:www
  rsync -a --delete private movb.de:www
else
  echo "Git reports unclean working copy -- can't continue."
fi

